openapi: 3.0.0
info:
  title: MCP Tool - reveal_contacts
  version: 1.0.0
paths:
  /mcp/reveal_contacts:
    post:
      summary: Reveal contact details for a list of UIDs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                uids:
                  type: array
                  items:
                    type: string
              required:
                - uids
      responses:
        '200':
          description: List of revealed contacts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
components:
  schemas:
    Contact:
      type: object
      properties:
        uid:
          type: string
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        company:
          type: string
        title:
          type: string
        linkedin:
          type: string
