# GitHub Labels Configuration
# This file defines the ONLY labels allowed in this repository
# DO NOT add labels manually - they will be removed by automation
# 
# Priority and Status are managed in GitHub Projects, not labels
# Type labels for issues, Discussion labels for tracking lifecycle

# Type Labels (mutually exclusive - issue should have exactly ONE)
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
  
- name: "feature"
  color: "0e8a16"
  description: "New feature or request"
  
- name: "enhancement"
  color: "a2eeef"
  description: "Improvement to existing functionality"
  
- name: "refactor"
  color: "f9d0c4"
  description: "Code improvement without changing functionality"
  
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
  
- name: "test"
  color: "bfd4f2"
  description: "Adding or updating tests"
  
- name: "chore"
  color: "fef2c0"
  description: "Maintenance tasks (deps, config, etc)"

# Discussion Status Labels (for tracking discussion lifecycle)
- name: "discussion:exploring"
  color: "c5def5"
  description: "Discussion is gathering feedback"
  
- name: "discussion:approved"
  color: "0e8a16"
  description: "Discussion approved for implementation"
  
- name: "discussion:in-progress"
  color: "ffd700"
  description: "Discussion being implemented"
  
- name: "discussion:implemented"
  color: "2ea44f"
  description: "Discussion has been implemented"
  
- name: "discussion:declined"
  color: "d93f0b"
  description: "Discussion won't be implemented"
  
- name: "discussion:blocked"
  color: "e99695"
  description: "Discussion blocked by dependencies"

# Auto-generated by bots (DO NOT MANUALLY ADD)
- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"

# Working State Labels (used by workflows)
- name: "state: stable"
  color: "2ea043"
  description: "Working state: STABLE"

- name: "state: working"
  color: "f2cc60"
  description: "Working state: WORKING"

- name: "state: wip"
  color: "fbca04"
  description: "Working state: WIP (draft/in progress)"

- name: "state: hotfix"
  color: "d73a49"
  description: "Working state: HOTFIX"
