#cloud-config
package_update: true
packages:
  - python3
  - python3-venv
  - python3-pip
  - git
  - nginx
runcmd:
  - systemctl stop nginx
  - systemctl disable nginx
  - ufw --force reset
  - ufw --force enable
  - ufw allow ssh
  - ufw allow http
  - ufw allow https
