#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3
  - python3-venv
  - python3-pip
  - git
  - nginx
  - ufw
runcmd:
  - ufw --force reset
  - ufw allow OpenSSH
  - ufw allow http
  - ufw allow https
  - ufw --force enable
  - mkdir -p /opt/signalhire
  - chown root:root /opt/signalhire
  - test -d /opt/signalhire/app || git clone --branch main --depth 1 https://github.com/vanman2025/signalhireagent.git /opt/signalhire/app
  - test -d /opt/signalhire/venv || python3 -m venv /opt/signalhire/venv
  - /opt/signalhire/venv/bin/pip install --upgrade pip
  - /opt/signalhire/venv/bin/pip install -r /opt/signalhire/app/requirements.txt
  - cp /opt/signalhire/app/scripts/serve_callback.py /opt/signalhire/serve_callback.py
  - cat <<'SERVICE' > /etc/systemd/system/signalhire-callback.service
    [Unit]
    Description=SignalHire Callback Server
    After=network.target

    [Service]
    Type=simple
    WorkingDirectory=/opt/signalhire/app
    Environment=PYTHONUNBUFFERED=1
    EnvironmentFile=-/opt/signalhire/app/.env
    ExecStart=/opt/signalhire/venv/bin/python /opt/signalhire/serve_callback.py --host 127.0.0.1 --port 8080
    Restart=on-failure
    RestartSec=5s

    [Install]
    WantedBy=multi-user.target
SERVICE
  - systemctl daemon-reload
  - systemctl enable --now signalhire-callback.service
  - rm -f /etc/nginx/sites-enabled/default
  - cat <<'NGINX' > /etc/nginx/sites-available/signalhire
    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass http://127.0.0.1:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /healthz {
            proxy_pass http://127.0.0.1:8080/healthz;
        }
    }
NGINX
  - ln -sf /etc/nginx/sites-available/signalhire /etc/nginx/sites-enabled/signalhire
  - systemctl enable nginx
  - systemctl restart nginx
